### PR TITLE
Add variable for Daily Waiver Reporting

### PR DESCRIPTION
**Pull request by tylersiskar**
Hey, not sure if this is something you had in the works already but I wanted to run it by you and get your thoughts. I saw you recently added the FAAB variable which is awesome, I had one request regarding it:

In my league, where we use free agent budget, all free agents are always on waiver. So each day, there could be waiver requests that go through. Our waivers also go through at noon, so i added the environment variable WAIVER_FREQUENCY that allows users to set to DAILY, otherwise it defaults to how you had it before.

Im not sure if you'd prefer a different way to accomplish this, or also allow the time of the standings/waiver reporting to be configured too, but just wanted to see what you thought of adding something like this.

Also: my prettier settings must have changed some of the lines so to make it easier the only changes I made are lines 642-645 and 670-677

### CODE REVIEW

**Comment by dtcarls** [comment]
Thank you! This is a great start on something I was planning on doing. I may make some modifications before merging it into master, but feel it's ready for develop.

**Comment by tylersiskar** [comment]
Sweet! Yeah feel free to modify however you'd like. Keep me posted on when you have it up on master so I can configure my bot to use it!

**Comment by tylersiskar** [comment]
@dtcarls Hey man, saw you merged into develop, I'm looking forward to using it when it's on master! One quick question - I saw you modified it a bit and it looks good, just wondering if we can add an environment variable for configuring the time the waiver report happens at? No worries if that's too much to have users configure, it's just that waivers go through at 12pm in my league, so it'd be best if the report happened around then. 
Thanks again!

**Comment by dtcarls** [comment]
Currently report times aren't configurable. It's something I'm looking at adding in the future, but not on my list in the near term. As a work around, you can merge this develop branch into your repo and change the times.

**Pull request merged**
