### PR TITLE
roll back espn_api update

### PR DESCRIPTION
**Pull request by dtcarls**

### CODE REVIEW

**Comment by dtcarls** [comment]
Update fixed 2 week playoffs, but broke everything else. Rolling back until resolved

**Comment by cwendt94** [comment]
Working on a fix now, I see the issue

**Comment by cwendt94** [comment]
Box score should now be fixed in v0.9.3 and two new fields `home_projected` and `away_projected`

**Comment by dtcarls** [comment]
thanks for the quick turnaround as always @cwendt94 , updating to latest again.

**Comment by cwendt94** [comment]
No problem, hopefully box scores I stable now 🤞!

**Pull request merged**
